### PR TITLE
Add ToggleMute function for Auxes

### PR DESCRIPTION
**Pull request by gertius1**
Dear Greg, 
I now added a function to toggle aux mutes, as this is an essential part of my mixing workflow.
This raises a few topics. I chose the M-Key modifier+Select to trigger the function in Aux mode.
But I see that the M-Key is not used for much else. Do you have it reserved somehow? I can put it on any other key combo that´s available. Another idea would be to also use "Aux Nr" + Track Select to trigger a function for that Aux, I don´t know how you feel about this.

Secondly, I thought it´s a good idea to have the Track Rec Led reflect the mute status:
- on is post
- blinking is pre
- off is mute

Mute is then still distinguished to "no aux" because the encoder rings stay lit.
Although the encoder rings have been a little bit buggy in aux mode and vanish from time to time on my machine, so I don´t know how you feel about it.

I would love to get a discussion going and hear your thoughts on this.

Best,
Christian

### CODE REVIEW

**Comment by Ruxton** [comment]
I think a better key is shift + mute WHEN in Aux mode.

So if you're in an aux, shift+mute becomes toggle bypass the aux, instead of the usual toggle bypass fx.

Reasoning is:
* select has HEAPS of things stuffed on it already
* mute seems a better key for this, its already functioning as a bypass toggle
* m_key isn't always available, if you turn meter mode on you wouldn't be able to use it
* because of this, most of the m_key's functions are

**Comment by gertius1** [comment]
Thanks for your message. I now changed the hotkey as you suggested, great idea!

One question in this regard, I designed the new function similar to the existing aux functions, extracting and modifying the string. But then when adjusting the LED code I found the API call GetSetTrackSendInfo ... to get the mute status. Do you know why the other aux functions did not use this GetSetTrackSendInfo function, but rather went through the string manipulation?

**Comment by gertius1** [comment]
I can see why adding and removing auxes would need to alter the string, but switching pre/post?

**Comment by gertius1** [comment]
Hi Greg, I added another fix for a bug in the original code, that would show when working with HW and AUX sends at the same time. 

Regarding my last pull request, I noticed that you haven´t approved it yet. Is there anything else you need from me before approving?

**Comment by Ruxton** [comment]
hey man thanks for the code, If you could use feature branches that'd be a big help.

eg. feature/blah_blahb_blah and then you can merge them into your master or whatever. There was a few things in that PR and made it hard to ascertain. 

I've just merged it to develop for now, while I work on cross-platform of the file-based plugin map thing. I think the better (and more cross platform) place for it is in the GetResourcesPath.

**Comment by gertius1** [comment]
Hi ruxton, thanks for accepting the pull request and thanks for making me aware of feature branches. I will use these in the future when developing new features.
Cool if you can add multiplatform to the plugin map.
Cheers!

**Pull request merged**
